### PR TITLE
added copyrights entry

### PR DESCRIPTION
**Pull request by karussell**

### CODE REVIEW

**Comment by karussell** [comment]
Ups, wrong thing. We need copyrights in the root doc not in every entry ...

**Comment by karussell** [comment]
Ah, we need a different response structure as well: https://github.com/karussell/GraphHopperNominatimConverter/commit/900bcfc459354af4999b4c551d3450ca207a2830

like

``` json
{"hits": [{}, ...]
"copyrights": ["", ..]
}
```

instead of just the 'raw hits'

``` json
[{}, ...]
```

**Comment by boldtrn** [comment]
Ah ok, thanks. So that's also included in #8 
I just tested it with Nominatim and it looks nice.

**Comment by karussell** [comment]
Ups, yes. Didn't intended to put all stuff in one PR (normally create an issue per feature) but now it is all a bit easier :)

**Comment by boldtrn** [comment]
No problem :+1: works well as long as not too many people are contributing. BTW: I just added the Copyright to the README (very tiny change).

**Pull request closed without merging**
