### PR TITLE
Introduce State District

### LINKED ISSUE #54: OCD Test is failing
The results for the test url of OCD seems to have changed over the time.

Related to #50.

Some time ago, OCD returned for:

https://api.opencagedata.com/geocode/v1/json?key=[KEY]&q=48.4882,2.6996&pretty=1

the county "Seine-et-Marne". Now the value "Seine-et-Marne" is returned in the field `state_district`. This would be fixable by falling back to state_district if county is not defined.

### PR DESCRIPTION
**Pull request by boldtrn**
Fixes #54 by falling back to `state_district` if `county` is not defined.

### CODE REVIEW

**Comment by boldtrn** [comment]
I just saw that [Nominatim also provides the field `state_district`.](https://wiki.openstreetmap.org/wiki/Nominatim#Hierarchy)

So I think it might be even better to add the state_district as a new field to the GHEntry?

**Comment by boldtrn** [comment]
But Nominatim [isn't returning it for our test case](https://nominatim.openstreetmap.org/reverse?format=jsonv2&lat=48.4882&lon=2.6996).

**Comment by boldtrn** [comment]
WDYT @karussell, should we create a new field in GHEntry?

**Comment by karussell** [comment]
Yes, a new field might be better

**Comment by boldtrn** [comment]
Ok, I updated the PR :)

**Review by karussell — APPROVED** [review]
Thanks :+1:

**Pull request merged**
