### PR TITLE
added IP filter

### PR DESCRIPTION
**Pull request by karussell**
a bit safe guarding the access like for GraphHopper. The usage is simple e.g. to restrict for local access only add to the yml:

ipWhiteList:"localhost,127.0.0.1"

### CODE REVIEW

**Comment by boldtrn** [comment]
Thanks for your PR. Great improvement!

> ipWhiteList:"localhost,127.0.0.1"

I think it would be a good idea to add the explanation to the .yml file. So people know how to use it.

BTW: It seems like we use a different code-style. I used my GraphHopper profile with curly braces wrapped on the new line.

**Comment by karussell** [comment]
> BTW: It seems like we use a different code-style. I used my GraphHopper profile with curly braces wrapped on the new line.

ups, sorry. I use normal Java guidelines everywhere and GraphHopper is a bit special with the brackets on the new line to make certain things more clear. Maybe we should switch there too.

**Comment by karussell** [comment]
Should I put the comment in the Java file (or config)?

**Comment by boldtrn** [comment]
> ups, sorry. I use normal Java guidelines everywhere and GraphHopper is a bit special with the brackets on the new line to make certain things more clear. Maybe we should switch there too.

Yes I like using standards. I can upload a standard code style.

> Should I put the comment in the Java file (or config)?

Mhm, maybe both. In the Java file we're setting the fallback/default, right? In my opinion the comment is more important in the yml, since most users will create their own.

**Pull request merged**
