### PR TITLE
Change house_number to housenumber

### PR DESCRIPTION
**Pull request by boldtrn**
This PR changes `house_number` to `housenumber` in the geocoding response.

### CODE REVIEW

**Comment by karussell** [comment]
Will this brake the API or was it broken before :) ?

**Comment by boldtrn** [comment]
> Will this brake the API or was it broken before :) ?

Yes that's the question :). If you look at the geocoding api with provider=default or at the [swagger](https://github.com/graphhopper/directions-api-clients/blob/master/swagger.json#L663), the geocoder-converter was broken and is now fixed. If you developed an app and used house_number it will break. We could for a limited time return `housenumber`and `house_number` and remove `house_number` later on?

**Comment by devemux86** [comment]
> If you developed an app and used house_number it will break.

Where do you mean, as [Geocoding API](https://docs.graphhopper.com/#tag/Geocoding-API) already uses the `housenumber` in JSON response?

**Comment by boldtrn** [comment]
> Where do you mean, as Geocoding API already uses the housenumber in JSON response?

Yes, that's correct :). The geocoder-converter behaved incorrectly as it returns `house_number` instead of `housenumber`. Some developers therefore might have used `house_number` instead.

If you use the Geocoding API and pass for example `provider=nominatim` it returns `house_number` if you use `provider=default` it returns `housenumber`. The documented value is `housenumber`, so I think the change here is OK.

**Comment by karussell** [comment]
Thanks for the explanation, this makes sense.

Let's deliver both values for now. (I'll contact customers in this regard and if they use the old house_number field ask them to migrate. And once this is safe we can remote the old way)

**Comment by boldtrn** [comment]
I added the change so that we now return `house_number` and `housenumber`.

**Comment by boldtrn** [comment]
Regarding the failing travis builds. This seems to be an issue with travis when trying to install jdk8 on xenial distros. I was able to fix this by pinning the distro to trusy, which [seems to be the recommendation](https://travis-ci.community/t/the-travis-ci-build-could-not-be-completed-due-to-an-error/1345/2).

**Comment by karussell** [comment]
Thanks, this is now already deployed :) :+1:

**Pull request merged**
