### PR TITLE
Improve documentation

### PR DESCRIPTION
**Pull request by boldtrn**
This PR improves the documentation. I tried to add some more information for a potential user and to give the whole document a bit more structure.

### CODE REVIEW

**Review by karussell — APPROVED** [review]

**Comment by karussell** [comment]
LGTM

Would you mind to add the limitations and supported features of the different providers also to the API documentation? https://github.com/graphhopper/directions-api/blob/master/geocoding.md

**Comment by boldtrn** [comment]
> Would you mind to add the limitations and supported features of the different providers also to the API documentation?

Yes I planned so :). I think before we should probably fix #40? Once the parameters are officially documented, changing them wouldn't be that easy anymore?

**Comment by karussell** [comment]
ok

> Once the parameters are officially documented, changing them wouldn't be that easy anymore?

Server side config params are not such a big issue

**Comment by boldtrn** [comment]
> Server side config params are not such a big issue

These are client parameters that can be added to the URL to change the results :).

**Comment by karussell** [comment]
Ups, sorry thought you were speaking of the url vs. URL .. ok, I would just not document those two parameters for now in #40

**Pull request merged**
